import { useEffect,useState } from "react"; import { useParams,Link } from "react-router-dom"; import { Github,ExternalLink,ArrowLeft } from "lucide-react"; import SEO from "../components/SEO"; import Loading from "../components/Loading"; import { loadJSON } from "../utils/api";
const toSlug=(p)=>p.slug||p.title.toLowerCase().replace(/[^a-z0-9]+/g,"-");
export default function ProjectDetail(){const {slug}=useParams();const [data,setData]=useState(null);const [missing,setMissing]=useState(false);
 useEffect(()=>{let active=true;setData(null);setMissing(false);
  loadJSON("/content/projects.json",[]).then(list=>{if(!active)return;const match=list.find(p=>toSlug(p)===slug);setData(match||null);setMissing(!match);});
  return()=>{active=false};},[slug]);
 // Without this an unknown slug (or missing projects.json) would spin on <Loading/> forever.
 if(missing)return <div className="container-page section max-w-3xl"><h1 className="page-title">Project not found</h1><p className="mt-5 body-copy">This case study doesn’t exist or has been renamed.</p><Link to="/projects" className="mt-8 inline-flex items-center gap-2 text-base font-semibold text-indigo-500"><ArrowLeft size={16}/> All projects</Link></div>;
 if(!data)return <Loading/>;return <div className="container-page section max-w-5xl"><SEO title={data.title} description={data.description} path={`/projects/${slug}`} type="article"/><Link to="/projects" className="mb-8 inline-flex items-center gap-2 text-base font-medium text-indigo-500"><ArrowLeft size={16}/> All projects</Link><h1 className="page-title">{data.title}</h1><p className="mt-5 max-w-3xl body-copy">{data.description}</p><div className="mt-6 flex flex-wrap gap-3">{data.github&&<a href={data.github} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl border border-slate-200 px-4 py-2 text-base dark:border-white/10"><Github size={17}/> GitHub</a>}{data.live_demo&&<a href={data.live_demo} target="_blank" rel="noreferrer" className="inline-flex items-center gap-2 rounded-xl bg-indigo-600 px-4 py-2 text-base font-semibold text-white"><ExternalLink size={17}/> Live demo</a>}</div><img src={data.image||"/images/project-placeholder.svg"} alt="" className="mt-10 w-full rounded-3xl border border-slate-200 dark:border-white/10"/><div className="mt-10 grid gap-10 lg:grid-cols-[1fr_280px]"><article className="prose-custom"><h2>Overview</h2><p>{data.description}</p>{data.challenges&&<><h2>Challenges</h2><p>{data.challenges}</p></>}{data.solution&&<><h2>Solution</h2><p>{data.solution}</p></>}{data.features?.length>0&&<><h2>Features</h2><ul>{data.features.map(x=><li key={x}>{x}</li>)}</ul></>}{data.architecture_image&&<><h2>Architecture</h2><img src={data.architecture_image} alt="Architecture diagram"/></>}{data.screenshots?.length>0&&<><h2>Screenshots</h2>{data.screenshots.map(x=><img key={x} src={x} alt="Project screenshot" loading="lazy"/>)}</>}</article><aside className="h-fit rounded-2xl border border-slate-200 p-5 dark:border-white/10"><h3 className="font-display text-lg font-semibold">Tech stack</h3><div className="mt-4 flex flex-wrap gap-2">{(data.technologies||[]).map(t=><span key={t} className="rounded-lg bg-slate-100 px-2 py-1 tag-text dark:bg-white/10">{t}</span>)}</div></aside></div></div>}
